# Generated by Django 3.1.7 on 2021-03-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('identity_key', models.CharField(max_length=128, unique=True, verbose_name='identity key')),
            ],
        ),
    ]
