# Generated by Django 3.1.7 on 2021-03-12 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psucontrol', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psu',
            options={'ordering': ['id'], 'verbose_name': 'Plant Supply Unit', 'verbose_name_plural': 'Plant Supply Units'},
        ),
        migrations.AddField(
            model_name='psu',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='psu',
            name='permitted_users',
            field=models.ManyToManyField(related_name='permitted_user', to=settings.AUTH_USER_MODEL, verbose_name='permitted users'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
