# Generated by Django 3.1.7 on 2021-03-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0003_auto_20210312_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('temperature', models.FloatField(verbose_name='temperature')),
                ('ground_humidity', models.FloatField(verbose_name='ground_humidity')),
                ('brightness', models.FloatField(verbose_name='brightness')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psucontrol.psu', verbose_name='Plant Supply Unit')),
            ],
        ),
    ]
