# Generated by Django 3.1.7 on 2021-03-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0006_auto_20210312_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datameasurement',
            options={'ordering': ['-timestamp', 'psu'], 'verbose_name': 'Data Measurement', 'verbose_name_plural': 'Data Measurements'},
        ),
    ]
