# Generated by Django 3.1.7 on 2021-03-12 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psucontrol', '0007_auto_20210312_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_key', models.CharField(max_length=128, unique=True, verbose_name='identity key')),
                ('pairing_key', models.CharField(max_length=6, unique=True, verbose_name='pairing key')),
            ],
            options={
                'verbose_name': 'Pending Plant Supply Unit',
                'verbose_name_plural': 'Pending Plant Supply Units',
                'ordering': ['pairing_key'],
            },
        ),
        migrations.AlterField(
            model_name='psu',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='authentication.user', verbose_name='owner'),
        ),
    ]
