# Generated by Django 3.1.7 on 2021-03-12 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0008_auto_20210312_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpsu',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='datameasurement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='pendingpsu',
            name='pairing_key',
            field=models.CharField(max_length=8, unique=True, verbose_name='pairing key'),
        ),
    ]
