# Generated by Django 3.1.7 on 2021-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0009_auto_20210312_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datameasurement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='timestamp'),
        ),
        migrations.AlterField(
            model_name='pendingpsu',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='pendingpsu',
            name='pairing_key',
            field=models.CharField(max_length=6, unique=True, verbose_name='pairing key'),
        ),
    ]
