# Generated by Django 3.1.7 on 2021-03-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0012_pendingpsu_public_rsa_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='psu',
            name='public_rsa_key',
            field=models.CharField(default='NONE', max_length=451, unique=True, verbose_name='public rsa key'),
            preserve_default=False,
        ),
    ]
