# Generated by Django 3.1.7 on 2021-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0014_psu_current_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datameasurement',
            name='timestamp',
            field=models.DateTimeField(verbose_name='timestamp'),
        ),
    ]
