# Generated by Django 3.1.7 on 2021-03-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0016_auto_20210320_1733'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datameasurement',
            unique_together={('psu', 'timestamp')},
        ),
    ]
