# Generated by Django 3.1.7 on 2021-04-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0018_communicationlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlogentry',
            name='request_url',
            field=models.CharField(default='none', max_length=200, verbose_name='request url'),
            preserve_default=False,
        ),
    ]
