# Generated by Django 3.1.7 on 2021-04-05 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0020_auto_20210402_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlogentry',
            name='psu_identity_key',
            field=models.CharField(default='NONE', max_length=128, verbose_name='psu identity key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communicationlogentry',
            name='psu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='psucontrol.psu', verbose_name='Plant Supply Unit'),
        ),
    ]
