# Generated by Django 3.2 on 2021-05-05 21:06

import django.core.files.storage
from django.db import migrations, models
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0026_auto_20210406_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingpsu',
            name='public_rsa_key',
            field=models.TextField(unique=True, verbose_name='public rsa key'),
        ),
        migrations.AlterField(
            model_name='psu',
            name='public_rsa_key',
            field=models.TextField(unique=True, verbose_name='public rsa key'),
        )
    ]
