# Generated by Django 3.2 on 2021-04-08 08:50

import django.core.files.storage
from django.db import migrations, models
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0026_auto_20210406_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psuimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/securemedia/', location='D:\\maxtech\\Documents\\Projects\\Python\\adveisor\\securemedia'), upload_to=psucontrol.models.upload_image_path, verbose_name='image'),
        ),
    ]
