# Generated by Django 3.2 on 2021-05-06 16:03

import django.core.files.storage
from django.db import migrations, models
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0027_auto_20210505_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datameasurement',
            name='air_humidity',
            field=models.FloatField(blank=True, null=True, verbose_name='air humidity'),
        ),
        migrations.AlterField(
            model_name='datameasurement',
            name='brightness',
            field=models.FloatField(blank=True, null=True, verbose_name='brightness'),
        ),
        migrations.AlterField(
            model_name='datameasurement',
            name='fill_level',
            field=models.FloatField(blank=True, null=True, verbose_name='fill level'),
        ),
        migrations.AlterField(
            model_name='datameasurement',
            name='ground_humidity',
            field=models.FloatField(blank=True, null=True, verbose_name='ground humidity'),
        ),
        migrations.AlterField(
            model_name='datameasurement',
            name='temperature',
            field=models.FloatField(blank=True, null=True, verbose_name='temperature'),
        ),
    ]
