# Generated by Django 3.2 on 2021-05-06 20:14

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0028_auto_20210506_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(-10, 'canceled'), (0, 'scheduled'), (5, 'approved'), (10, 'received'), (20, 'done')], verbose_name='status')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('timestamp_execution', models.DateTimeField(blank=True, verbose_name='execution timestamp')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pflanzenpflegestation', to='psucontrol.psu')),
            ],
            options={
                'verbose_name': 'Watering Task',
                'verbose_name_plural': 'Watering Tasks',
                'ordering': ['-timestamp', 'status'],
            },
        ),
    ]
