# Generated by Django 3.2 on 2021-05-06 20:37

import django.core.files.storage
from django.db import migrations, models
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0030_auto_20210506_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateringtask',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
