# Generated by Django 3.2 on 2021-05-06 20:59

import django.core.files.storage
from django.db import migrations, models
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0031_auto_20210506_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateringtask',
            name='status',
            field=models.IntegerField(choices=[(-10, 'canceled'), (0, 'scheduled'), (5, 'approved'), (10, 'transmitted'), (20, 'done')], default=0, verbose_name='status'),
        ),
    ]
