# Generated by Django 3.2 on 2021-05-07 10:59

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0032_auto_20210506_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringParams',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('ground_humidity_goal', models.FloatField(verbose_name='ground humidity goal')),
                ('light_level_limit', models.FloatField(help_text='Light limit to prevent watering in the mid of the night.', verbose_name='light level limit')),
                ('temperature_limit', models.FloatField(help_text='Temperature limit to prevent watering in too hot periods.', verbose_name='temperature limit')),
                ('kp', models.FloatField(help_text='Multiplier for the proportional part.', verbose_name='Kp')),
                ('ki', models.FloatField(help_text='Multiplier for the integral part.', verbose_name='Ki')),
                ('kd', models.FloatField(help_text='Multiplier for the derivative part.', verbose_name='Kd')),
                ('dt', models.FloatField(help_text='Duration of one timestep.', verbose_name='dt')),
            ],
            options={
                'verbose_name': 'Watering Parameters',
                'verbose_name_plural': 'Watering Parameters',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='psu',
            name='unauthorized_watering',
            field=models.BooleanField(default=False, verbose_name='unauthorized watering'),
        ),
        migrations.AddField(
            model_name='psu',
            name='watering_params',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='psucontrol.wateringparams', verbose_name='watering parameters'),
        ),
    ]
