# Generated by Django 3.2 on 2021-05-08 15:28

import django.core.files.storage
from django.db import migrations, models
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0033_auto_20210507_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringparams',
            name='minimum_amount',
            field=models.IntegerField(default=40, help_text='The minimum amount of water which should be used for the watering.', verbose_name='minimum amount'),
        ),
        migrations.AddField(
            model_name='wateringparams',
            name='starting_amount',
            field=models.IntegerField(default=40, help_text='The amount of water which is used to test how many water is needed.', verbose_name='starting amount'),
        ),
        migrations.AlterField(
            model_name='wateringparams',
            name='ground_humidity_goal',
            field=models.FloatField(default=80, verbose_name='ground humidity goal'),
        ),
        migrations.AlterField(
            model_name='wateringparams',
            name='light_level_limit',
            field=models.FloatField(default=10, help_text='Light limit to prevent watering in the mid of the night.', verbose_name='light level limit'),
        ),
        migrations.AlterField(
            model_name='wateringparams',
            name='temperature_limit',
            field=models.FloatField(default=27, help_text='Temperature limit to prevent watering in too hot periods.', verbose_name='temperature limit'),
        ),
    ]
