# Generated by Django 3.2 on 2021-05-07 09:29

import django.core.files.storage
from django.db import migrations, models
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0033_auto_20210507_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psu',
            old_name='watering_alogrithm',
            new_name='watering_algorithm',
        ),
    ]
