# Generated by Django 3.2 on 2021-05-08 16:42

import django.core.files.storage
from django.db import migrations, models
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0034_auto_20210508_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringparams',
            name='maximum_amount',
            field=models.IntegerField(default=100, help_text='The maximum amount of water which should be used for the watering.', verbose_name='maximum amount'),
        ),
    ]
