# Generated by Django 3.2 on 2021-05-08 16:51

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import psucontrol.models


class Migration(migrations.Migration):

    dependencies = [
        ('psucontrol', '0035_auto_20210508_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('info', models.TextField(verbose_name='information')),
                ('psu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psucontrol.psu', verbose_name='Plant Supply Unit')),
                ('watering_params', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psucontrol.wateringparams', verbose_name='watering parameters')),
            ],
            options={
                'verbose_name': 'Watering Decision',
                'verbose_name_plural': 'Watering Decisions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
